apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: 287870619543.dkr.ecr.us-east-1.amazonaws.com/auth:2
        ports:
        - containerPort: 3001
