apiVersion: apps/v1
kind: Deployment
metadata:
  name: linodeapp-auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: linodeapp-auth
  template:
    metadata:
      labels:
        app: linodeapp-auth
    spec:
      containers:
      - name: linodeapp-auth
        image: saba2002/linodeapp-auth:latest
        ports:
        - containerPort: 3001
