apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        image: 287870619543.dkr.ecr.us-east-1.amazonaws.com/admin:42
        ports:
        - containerPort: 3000
